### ISSUE TITLE
not able to connect with keycloack

### ISSUE THREAD

**Issue by hiraghuak** [chunky-monkeys/keycloak-client#47]
Hi, 

i'm not able to connect with keycloack please help me with this. Getting "Internal Server Error" 
this is my code: https://github.com/hiraghuak/flask-keycloak

**Comment by akhilputhiry** [comment]
You are using a public client. Need to use confidential client.

<img width="1217" alt="Screenshot 2020-05-17 at 10 17 30 AM" src="https://user-images.githubusercontent.com/747410/82136110-ae154f00-9827-11ea-892b-40349667ec63.png">

**Comment by hiraghuak** [comment]
hey @akhilputhiry thank you very much for your guidance, im sucessfuly connecte my flask app with keycloack, but i'm getting "Invalid parameter: redirect_uri" error, 
 
![error-msg](https://user-images.githubusercontent.com/17245017/82157304-3c2c1c80-989e-11ea-9b8f-4e7d8df02689.png)


![invalid-url](https://user-images.githubusercontent.com/17245017/82157269-0850f700-989e-11ea-9235-6a9a5050db01.png)

**Comment by akhilputhiry** [comment]
See the example

https://github.com/chunky-monkeys/keycloak-client/blob/master/examples/flask-app/app.py

**Comment by hiraghuak** [comment]
@akhilputhiry  getting error " ypeError: __init__() got an unexpected keyword argument 'callback_url'
Traceback (most recent call last) "

my code: https://github.com/hiraghuak/flask-keycloak

![typeError](https://user-images.githubusercontent.com/17245017/82282035-830a3700-99b0-11ea-9f4d-261dbeb181c0.png)

**Comment by akhilputhiry** [comment]
Could you try with the latest version? Upgrade using `pip install keycloak --upgrade` and try again.

**Comment by hiraghuak** [comment]
Hi @akhilputhiry  i have found solution its  **"callback_uri"**  (not callback_url). not **_url** right one is **_uri** please update document.

api.wsgi_app = AuthenticationMiddleware(
    api.wsgi_app,
    api.config,
    api.session_interface,
    callback_uri="http://localhost:5000/kc/callback",
    redirect_uri="/howdy",
)

**Comment by hiraghuak** [comment]
@akhilputhiry updated keycloak its working. and after login getting **"Invalid state"** error

**Comment by akhilputhiry** [comment]
@hiraghuak I do not see any reason for a 403 to happen. Your environment might be corrupted or something. The following piece of code is personally tested and verified. If this is not working in your machine, it means your environment is corrupted.

```from flask import Flask, session
from keycloak import Client
from keycloak.extensions.flask import AuthenticationMiddleware


api = Flask(__name__)
api.config["SECRET_KEY"] = "secret0123456789"
api.wsgi_app = AuthenticationMiddleware(
    api.wsgi_app,
    api.config,
    api.session_interface,
    callback_url="http://localhost:5000/kc/callback",
    redirect_url="/howdy",
)

kc = Client()

@api.route("/howdy")
def howdy():
    user = session["user"]
    return f"Howdy {user}"


if __name__ == '__main__':
    api.run(host='0.0.0.0')```

**Comment by hiraghuak** [comment]
@akhilputhiry, I have successfully able to connect keycloak, exactly issue is when hitting to "http://localhost:5000/howdy" url getting error **"Invalid state"** and I have made screen recording, pushed working code git

and I have verified my environment its working.

**screen recording:** https://drive.google.com/file/d/1yhr5yh6i3QZUDHCAw_98jjYWnXrKXTiG/view?usp=sharing

**git link :** https://github.com/hiraghuak/flask-keycloak

and need help on integrating keycloak Rest api with python flask.

**Comment by akhilputhiry** [comment]
@hiraghuak you are mixing things up. Pardon me for the bad documentation.

If you are using middleware you dont have to implement `login`, `callback` and `logout`
you just need to use the middleware everything is taken care inside it.
The middleware automatically creates a route called `/kc/callback`.
Just replace your `app.py` with the following.

```
# -*- coding: utf-8 -*-
import json
from typing import Dict, Callable
from flask import Flask, redirect, request, jsonify, session, Response, render_template, url_for, Config
from flask import Request
from keycloak.extensions.flask import AuthenticationMiddleware
from flask.sessions import SessionInterface
from werkzeug.wrappers import Response


api = Flask(__name__)
api.config["SECRET_KEY"] = "secret0123456789"
api.wsgi_app = AuthenticationMiddleware(
    api.wsgi_app,
    api.config,
    api.session_interface,
    callback_url="http://localhost:5000/kc/callback",
    redirect_url="http://localhost:5000/howdy",
)


@api.route('/')
@api.route('/home')
def hello_world():
    return render_template('home.html')


@api.route('/about')
def about():
    return render_template('about.html', title='about')


@api.route('/contact')
def contact():
    return render_template('contact.html', title='contact')


@api.route("/howdy")
def howdy():
    user = session["user"]
    return f"Howdy {user}"


if __name__ == '__main__':
    api.run(host='0.0.0.0')

```

**Comment by akhilputhiry** [comment]
I hope this is good to close now. Please re-open in case you need any help.
