### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by nikkiedd** [chunky-monkeys/keycloak-client#48]
I'm using this library to authenticate users in Django. How could I deauthenticate them? I see no logout method, and deleting the current session didn't work.

Thank you!

**Comment by akhilputhiry** [comment]
Hi @nikkiedd I have added the logout feature in https://github.com/chunky-monkeys/keycloak-client/pull/49. Will make a release after validation.

**Comment by nikkiedd** [comment]
This is great. Thank you very much for your quick reply! :)
