### ISSUE TITLE
Starlette example logout not working properly

### ISSUE THREAD

**Issue by ybinnenwegin2ip** [chunky-monkeys/keycloak-client#53]
Hello,

While trying out the Starlette example from [here](https://github.com/chunky-monkeys/keycloak-client/blob/master/examples/starlette-app/app.py) I noticed that the logout endpoint doesn't work as intended.

The logout functionality itself works fine, but the "User logged out successfully" response is never shown, instead it returns an HTTP status 204 (no content) and the browser remains on the same page. I believe this is caused by the fact that the [`Logout` class](https://github.com/chunky-monkeys/keycloak-client/blob/master/src/keycloak/extensions/starlette.py#L28) returns a `Response` rather than the request, which does happen in the flask extension for example. Because a `Response` is returned the user-defined `/logout` route is never called and thus the logout message is never shown.

As for a solution for this, I don't have one yet. I'm going to play around with Starlette middlewares and see if I can come up with a fix.

**Comment by ybinnenwegin2ip** [comment]
Well I have something that seems to function as it should. However it should be noted I'm not an ASGI expert by any means.

This is my resulting `starlette.py` file:

```python
# -*- coding: utf-8 -*-
import json
from typing import Any
from urllib.parse import urlparse

from starlette.types import ASGIApp, Receive, Scope, Send
from starlette.requests import Request
from starlette.responses import Response, RedirectResponse, PlainTextResponse
from starlette.endpoints import HTTPEndpoint

from .. import Client


class EndpointHandler(HTTPEndpoint):
    def __init__(self, *args: Any, **kwargs: Any):
        self.kc = kwargs.pop("kc")
        self.redirect_uri = kwargs.pop("redirect_uri", "/")
        super().__init__(*args, **kwargs)


class Login(EndpointHandler):
    async def get(self, request: Request) -> Response:
        url, state = self.kc.login()
        request.session["state"] = state
        return RedirectResponse(url)


class Callback(EndpointHandler):
    async def get(self, request: Request) -> Response:

        # validate state
        state = request.query_params["state"]
        _state = request.session.pop("state", "unknown")
        if state != _state:
            return PlainTextResponse("Invalid state", status_code=403)

        # retrieve tokens
        code = request.query_params["code"]
        tokens = self.kc.callback(code)
        # request.session["tokens"] = json.dumps(tokens)

        # retrieve user info
        access_token = tokens["access_token"]
        user = self.kc.fetch_userinfo(access_token)
        request.session["user"] = json.dumps(user)

        return RedirectResponse(self.redirect_uri)


class AuthenticationMiddleware:
    def __init__(
        self,
        app: ASGIApp,
        callback_url: str = "https://localhost:8000/kc/callback",
        redirect_uri: str = "/",
        logout_uri: str = "/kc/logout",
    ) -> None:
        self.app = app
        self.callback_url = callback_url
        self.redirect_uri = redirect_uri
        self.logout_uri = logout_uri
        self.kc = Client(callback_url)

    @staticmethod
    def get_url(request: Request) -> str:
        return f"{request.url.scheme}://{request.url.netloc}{request.url.path}"

    @staticmethod
    def is_http(scope: Any) -> bool:
        return scope["type"] == "http"

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:

        # handle http requests
        if self.is_http(scope):
            request = Request(scope, receive)
            print("===>", self.get_url(request))

            # handle callback request
            if self.get_url(request) == self.callback_url:
                await Callback(
                    scope, receive, send, kc=self.kc, redirect_uri=self.redirect_uri
                )
                return

            # handle unauthorized requests
            elif "user" not in request.session:
                await Login(scope, receive, send, kc=self.kc)
                return

            # handle logout request
            elif request.url.path == self.logout_uri:
                del request.session["user"]
                await self.app(scope, receive, send)
                return

            # handle authorized requests
            else:
                await self.app(scope, receive, send)
                return

        # handle non http requests
        await self.app(scope, receive, send)
```

The if-statement for checking if "user" is within the session has also been moved up. This prevents an internal server error from occurring when someone accesses `/logout` when they're not logged in.

**Comment by akhilputhiry** [comment]
Thank you @ybinnenwegin2ip I will check this shortly. Thank you for your patience.

**Comment by akhilputhiry** [comment]
Its because of the status code `204`
I think the new versions of browsers dont allow any content to be sent along with 204 status code
I have made the changes in the master branch

@ybinnenwegin2ip could you please verify the same against master branch

closing this for now. Feel free to reopen if your issue has not resolved.

Thanks

**Comment by ybinnenwegin2ip** [comment]
> Its because of the status code `204`
> I think the new versions of browsers dont allow any content to be sent along with 204 status code
> I have made the changes in the master branch
> 
> @ybinnenwegin2ip could you please verify the same against master branch
> 
> closing this for now. Feel free to reopen if your issue has not resolved.
> 
> Thanks

This has indeed solved the issue of the "User logged out successfully" response never being shown. Thanks a lot! :)
