### ISSUE TITLE
Keycloak response is expecting JSON, but keycloak 11.0.3 is returning bytest for userinfo endpoint

### ISSUE THREAD

**Issue by jmath1** [chunky-monkeys/keycloak-client#54]
I am trying to implement the keycloak client using flask. When it calls the userinfo endpoint, the endpoint is returning a bytes string in the body. The client is expecting JSON. Which version of keycloak is this made for?

**Comment by akhilputhiry** [comment]
I have tested this against `Keycloak - Version 11.0.3` and its working fine. If you could share more information regarding the error it would be more helpful

**Comment by akhilputhiry** [comment]
Hi @jmath1 I am closing this thread since there is no communication over this. Feel free to re-open if needed. Thanks.
