### ISSUE TITLE
Error while fetching userinfo

### ISSUE THREAD

**Issue by Biboba** [chunky-monkeys/keycloak-client#55]
Hello,

Following your documentation example:
https://keycloak-client.readthedocs.io/en/latest/features/authentication.html

I receive the error below:
"requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url"
at the following line:
```
kc.userinfo(access_token)
```

Thanks !

**Comment by akhilputhiry** [comment]
HI @Biboba 

Thank you for your patience

The correct usage is `kc.fetch_userinfo(access_token)`
I have also updated the documentation accordingly

**Comment by Biboba** [comment]
Hi @akhilputhiry 

Thanks for the information and for the documentation update.
I confirm that it works now using 'fetch_userinfo'.
